app_doctor/urls.py
from django.contrib import admin
from django.urls import path

from app_doctor.views import *

app_name = 'app_doctor'

urlpatterns = [
    path('', OrderList.as_view(), name='home'),
    path('doctor/location/<int:pk>', DoctorLocationAPIView.as_view(), name='doctor_location'),
    path('order/create/', OrdersApiCreate.as_view(), name='order_create'),
    path('orders/list/', OrderList.as_view(), name='orders_list'),
    path('doctors/list/', DoctorList.as_view(), name='doctors_list'),
    path('orders/update/<int:pk>', OrderUpdateView.as_view(), name='order_update'),
    path('doctors/update/<int:pk>', DoctorUpdateView.as_view(), name='doctor_update'),
    path('route/add/<int:order_id>/<int:name>', RouteAdd.as_view(), name='add_route'),
    path('route/update/<int:order_id>/<int:name>', RouteUpdate.as_view(), name='route_update'),
    path('route/detail/<int:pk>', RouteDetail.as_view(), name='route_detail'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
]

doctor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_doctor/', include('app_doctor.urls')),
]

templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'app_doctor:home' %}" class="nav-link px-2 text-secondary">Главная</a></li>
                <li><a href="{% url 'app_doctor:order_create' %}" class="nav-link px-2 text-white">Создать
                    заявку(Пациент)</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'app_doctor:doctor_location' request.user.id %}"
                           class="nav-link px-2 text-white">Отметится в текущем местоположении(Доктор)</a>
                    </li>

                {% else %}
                {% endif %}
                <li>
                    <a class="nav-link px-2 text-white" href="{% url 'app_doctor:doctors_list' %}">Информация о
                        врачах</a>
                </li>


            </ul>
            <!-- add auth set -->
            <div class="text-end navbar-text">
                {% if request.user.is_authenticated %}
                    <a href="">Привет, {{ request.user.username }} |</a>
                    <div class="btn btn-primary" onclick="location.href='{% url 'app_doctor:logout' %}'">
                        <span>logout</span>
                        {% else %}
                    </div>
                    <div class="btn btn-warning" onclick="location.href='{% url 'app_doctor:register' %}'">
                        <span>register</span>
                    </div>
                    <div class="btn btn-info" onclick="location.href='{% url 'app_doctor:login' %}'">
                        <span>login</span>
                    </div>
                {% endif %}


            </div>
        </div>
    </div>
</header>