app_doctor/urls.py
from django.contrib import admin
from django.urls import path

from app_doctor.views import *

app_name = 'app_doctor'

urlpatterns = [
    path('', OrderList.as_view(), name='home'),
    path('doctor/location/<int:pk>', DoctorLocationAPIView.as_view(), name='doctor_location'),
    path('order/create/', OrdersApiCreate.as_view(), name='order_create'),
    path('orders/list/', OrderList.as_view(), name='orders_list'),
    path('doctors/list/', DoctorList.as_view(), name='doctors_list'),
    path('orders/update/<int:pk>', OrderUpdateView.as_view(), name='order_update'),
    path('doctors/update/<int:pk>', DoctorUpdateView.as_view(), name='doctor_update'),
    path('route/add/<int:order_id>/<int:name>', RouteAdd.as_view(), name='add_route'),
    path('route/update/<int:order_id>/<int:name>', RouteUpdate.as_view(), name='route_update'),
    path('route/detail/<int:pk>', RouteDetail.as_view(), name='route_detail'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
]

doctor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_doctor/', include('app_doctor.urls')),
]

app_doctor/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from geopy.distance import geodesic as GD
from geopy import distance


class Doctor(models.Model):
    name = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    latitude = models.DecimalField(max_digits=10, decimal_places=7, verbose_name='Начальная Широта геолокация врача',
                                   default=0)
    longitude = models.DecimalField(max_digits=10, decimal_places=7, verbose_name='Начальная Долгота геолокация врача',
                                    default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name.get_full_name()


class Orders(models.Model):
    doc_name = models.ForeignKey(Doctor, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Назначен врач')
    latitude = models.DecimalField(max_digits=10, decimal_places=7, verbose_name='Широта геолокация пациента')
    longitude = models.DecimalField(max_digits=10, decimal_places=7, verbose_name='Долгота геолокация пациента')
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    patient_name = models.CharField(max_length=50)
    is_active = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self):
        return f'"{self.patient_name}" - {self.text[:50]}'

    def get_distance(self):
        if self.doc_name:
            patient_geo = (self.latitude, self.longitude)
            doctor_geo = (self.doc_name.latitude, self.doc_name.longitude)
            return float('{:.1f}'.format(distance.distance(doctor_geo, patient_geo).km))


class Route(models.Model):
    doc_name = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    latitude = models.DecimalField(max_digits=10, decimal_places=7, verbose_name='По маршрута Широта геолокация врача')
    longitude = models.DecimalField(max_digits=10, decimal_places=7,
                                    verbose_name='По маршруту Долгота геолокация врача')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.order}'

    def get_curent_time_in_work(self):
        return timezone.now() - self.timestamp

    def get_distance(self):
        if self.doc_name:
            patient_geo = (self.order.latitude, self.order.longitude)
            doctor_geo = (self.latitude, self.longitude)
            return float('{:.1f}'.format(distance.distance(doctor_geo, patient_geo).km))

app_doctor/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from app_doctor.models import Doctor, Orders, Route


class DoctorForm(ModelForm):
    class Meta:
        model = Doctor
        fields = ['name', 'latitude', 'longitude']

        # widgets = {
        #     'name': forms.Select(attrs={
        #         'class': 'form-control',
        #     }),
        #     'latitude': forms.CharField(attrs={
        #         'class': 'form-control',
        #     }),
        #     'longitude': forms.CharField(attrs={'class': 'form-control'}),
        # }


class OrdersClientForm(ModelForm):
    class Meta:
        model = Orders
        fields = ['patient_name', 'text', 'latitude', 'longitude']


class OrdersUpdateForm(ModelForm):
    class Meta:
        model = Orders
        fields = ['doc_name', 'patient_name', 'text', 'is_active']


class RouteForm(ModelForm):
    class Meta:
        model = Route
        fields = ['doc_name', 'order', 'latitude', 'longitude']

class RouteFormUpdate(ModelForm):
    class Meta:
        model = Route
        fields = ['doc_name', 'order', 'latitude', 'longitude']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(
        attrs={"class": "form-control", 'placeholder': "Username max 150"}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={"class": "form-control", 'placeholder': "Пароль"}))


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(
        attrs={"class": "form-control", 'placeholder': "Username max 150"}))
    email = forms.EmailField(label='E-mail',
                             widget=forms.EmailInput(attrs={"class": "form-control", 'placeholder': "email"}))
    first_name = forms.CharField(label='Имя',
                                 widget=forms.TextInput(attrs={"class": "form-control", 'placeholder': "Имя"}))
    last_name = forms.CharField(label='Фамилия',
                                widget=forms.TextInput(attrs={"class": "form-control", 'placeholder': "Фамилия"}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={"class": "form-control", 'placeholder': "Пароль"}))
    password2 = forms.CharField(label='Повторить пароль', widget=forms.PasswordInput(
        attrs={"class": "form-control", 'placeholder': "Повторить пароль"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

app_doctor/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from rest_framework.response import Response
from django.contrib import messages
from .forms import *
from .models import *


class DoctorLocationAPIView(UpdateView):
    template_name = 'doctor.html'
    form_class = DoctorForm
    success_url = reverse_lazy(
        'app_doctor:home')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Doctor.objects.get(name=id)


class OrdersApiCreate(CreateView):
    template_name = 'order.html'
    form_class = OrdersClientForm
    success_url = reverse_lazy(
        'app_doctor:home')


class OrderList(ListView):
    model = Orders
    template_name = 'table.html'
    context_object_name = 'orders'
    queryset = Orders.objects.order_by('-timestamp')


class OrderUpdateView(UpdateView):
    template_name = 'order_update.html'
    form_class = OrdersUpdateForm
    success_url = reverse_lazy(
        'app_doctor:home')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Orders.objects.get(pk=id)


class DoctorUpdateView(UpdateView):
    template_name = 'doctor_update.html'
    form_class = DoctorForm
    success_url = reverse_lazy(
        'app_doctor:doctors_list')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Doctor.objects.get(pk=id)


class RouteAdd(CreateView):
    template_name = 'route_add.html'
    form_class = RouteForm
    success_url = reverse_lazy(
        'app_doctor:home')

    def get_initial(self):
        initial = super(RouteAdd, self).get_initial()
        order_id = self.kwargs["order_id"]
        name = self.kwargs["name"]
        initial['doc_name'] = name
        initial['order'] = order_id
        return initial


class DoctorList(ListView):
    model = Doctor
    template_name = 'doctors_info.html'
    context_object_name = 'doctors'
    queryset = Doctor.objects.all()


def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('app_doctor:home')
    else:
        form = UserLoginForm()

    return render(request, 'login.html', {"form": form})


def user_logout(request):
    logout(request)
    return redirect('app_doctor:login')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Регистрация успешна')
            return redirect('app_doctor:home')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()

    return render(request, 'register.html', {"form": form})


class RouteDetail(DetailView):
    model = Orders
    template_name = 'route.html'
    context_object_name = 'order'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RouteDetail, self).get_context_data(**kwargs)
        order_id = self.kwargs.get('pk', None)
        context['route'] = Route.objects.get(order=order_id)
        return context


class RouteUpdate(UpdateView):
    model = Route
    template_name = 'route_update.html'
    form_class = RouteFormUpdate

    def get_object(self, **kwargs):
        order_id = self.kwargs["order_id"]
        name = self.kwargs["name"]
        return Route.objects.get(order=order_id, doc_name=name)

    def get_success_url(self):
        order_id = self.kwargs["order_id"]
        return reverse("app_doctor:route_detail", kwargs={"pk": order_id})

app_doctor/templates/doctor.html
{% extends 'layout/base.html' %}
{% block content %}
<h3>Doctor Information</h3>
<button class="btn-geo btn btn-danger">Geoposition</button>
<form method="POST">
 {% csrf_token %}
 {{ form.as_p }}

   <input class="btn btn-success" type="submit" value="Add">
</form>
{% endblock %}

app_doctor/templates/doctor_update.html
{% extends 'layout/base.html' %}
{% block content %}
<h3>Doctor update</h3>
<button class="btn-geo btn btn-danger">Geoposition</button>
<form method="POST">
 {% csrf_token %}
 {{ form.as_p }}

   <input class="btn btn-success" type="submit" value="Add">
</form>
{% endblock %}

app_doctor/templates/doctors_info.html
{% extends 'layout/base.html' %}
{% block content %}
    <h3>Doctors manager</h3>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Actions</th>
            <th scope="col">id</th>
            <th scope="col">Врач</th>
            <th scope="col">Время последней отметки</th>
            <th scope="col">Гео врача</th>
        </tr>
        </thead>
        <tbody>
        {% for data in doctors %}
            <tr>
                <td><a href="{% url 'app_doctor:doctor_update' data.id %}">Отметиться в текущем местоположении</a></td>
                <td>{{ data.id }}</td>
                <td>{{ data.name.get_full_name }}</td>
                <td>{{ data.timestamp }}</td>
                {% if data.timestamp and data.longitude %}
                    <td><a href="https://yandex.ru/maps/?pt={{ data.longitude }},{{ data.latitude }}&z=18&l=map">Геопозиция
                        врача</a></td>
                {% else %}
                    <td>Данные не преоставлены</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

app_doctor/templates/login.html
{% extends 'layout/base.html' %}
{% block content %}
    <div class="container min-vh-100 d-flex justify-content-center align-items-center">
        <form method="post">
            {% csrf_token %}
            <h3 align="center">Логин</h3>
            <br>
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-primary btn-block">Войти</button>
        </form>
    </div>
{% endblock %}

app_doctor/templates/order.html
{% extends 'layout/base.html' %}
{% block content %}
<h3>Frontend client</h3>
<button class="btn-geo btn btn-danger">Предоставить геопозицию</button>
<form method="POST">
 {% csrf_token %}
 {{ form.as_p }}

   <input class="btn btn-success" type="submit" value="Add">
</form>
{% endblock %}

app_doctor/templates/order_update.html
{% extends 'layout/base.html' %}
{% block content %}
<h3>Order update</h3>
<button class="btn-geo btn btn-danger">Geoposition</button>
<form method="POST">
 {% csrf_token %}
 {{ form.as_p }}

   <input class="btn btn-success" type="submit" value="Add">
</form>
{% endblock %}

app_doctor/templates/register.html
{% extends 'layout/base.html' %}

{% block content %}

    <div class="container min-vh-100 d-flex justify-content-center align-items-center">
        <form method="post">
            {% csrf_token %}
            <h3 align="center">Регистрация</h3>
            <br>
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-primary btn-block">Регистрация</button>
        </form>
    </div>

{% endblock %}

app_doctor/templates/route.html
{% extends 'layout/base.html' %}
{% block content %}
    <div class="card text-center">
        <div class="card-header">
            id {{ order.id }}, Врач- {{ order.doc_name }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Пациент - {{ order.patient_name }}</h5>
            <p class="card-text">Описание заявки - {{ order.text }}</p>
            <a class="btn btn-primary"
               href="https://yandex.ru/maps/?pt={{ order.longitude }},{{ order.latitude }}&z=18&l=map">Геопозиция
                пациета</a>
            <a class="btn btn-primary"
               href="https://yandex.ru/maps/?pt={{ route.longitude }},{{ route.latitude }}&z=18&l=map">Геопозиция
                врача</a>
            <a class="btn btn-primary"
               href="https://yandex.ru/maps/?rtext={{ order.latitude }},{{ order.longitude }}~{{ route.latitude }},{{ route.longitude }}&rtt=auto
">Маршрут</a>
            <p class="card-text"><a class="btn btn-danger"
               href="{% url 'app_doctor:route_update' order_id=order.id name=order.doc_name.id %}">Поставить отметку о
                позиции по маршруту</a></p>
            <p class="card-text"><span
                    class="badge bg-primary">Расстояние до доктора - {{ route.get_distance }} км</span></p>
            <p class="card-text"><span class="badge bg-info">Заявка добавлена в маршрут - {{ route.timestamp }}</span>
            </p>
            <p class="card-text"><span class="badge bg-info">В пути - {{ route.get_curent_time_in_work }}</span></p>

        </div>
        <div class="card-footer text-body-secondary">
            Дата получения заявки {{ order.timestamp }}
        </div>
    </div>
{% endblock %}

app_doctor/templates/route_add.html
{% extends 'layout/base.html' %}
{% block content %}
<h3>Route</h3>
<button class="btn-geo btn btn-danger">Предоставить геопозицию</button>
<form method="POST">
 {% csrf_token %}
 {{ form.as_p }}

   <input class="btn btn-success" type="submit" value="Add">
</form>
{% endblock %}

app_doctor/templates/route_update.html
{% extends 'layout/base.html' %}
{% block content %}
<h3>Route update</h3>
<button class="btn-geo btn btn-danger">Предоставить геопозицию</button>
<form method="POST">
 {% csrf_token %}
 {{ form.as_p }}

   <input class="btn btn-success" type="submit" value="Add">
</form>
{% endblock %}

app_doctor/templates/table.html
{% extends 'layout/base.html' %}
{% block content %}
    <h3>Заявки</h3>
    <ol class="list-group list-group-numbered">
        <li class="list-group-item">Нажимаем Edit, добавляем врача к заявке, ставим статус Active</li>
        <li class="list-group-item">В информации о врачах, отмечаемся в текущем местоположении</li>
        <li class="list-group-item">На главной странице добавляем заявку в маршрут</li>
    </ol>
    <table class="table table-hover fixed-columns">
        <thead>
        <tr>
            <th scope="col">Actions</th>
            <th scope="col">Врач</th>
            <th scope="col">Имя пациета</th>
            <th scope="col">Время записи</th>
            <th scope="col">Обращение</th>
            <th scope="col">В работе</th>

            <th scope="col">Маршрут</th>

        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            {% if order.is_active %}
            <tr class="table-info">
            {% else %}
            <tr>
            {% endif %}
                <td>
                    <a href="{% url 'app_doctor:order_update' order.id %}">Edit</a>
                    {% if order.is_active %}
                        <a class="link-success"
                           href="{% url 'app_doctor:add_route' order_id=order.id name=order.doc_name.id %}">В маршрут</a>
                    {% else %}
                        <p>Не в работе</p>
                    {% endif %}
                </td>
                <th scope="row">{{ order.doc_name }}</th>
                <td>{{ order.patient_name }}</td>
                <td>{{ order.timestamp }}</td>
                <td>{{ order.text }}</td>
                <td>{{ order.is_active }}</td>
            {% if order.is_active %}
            <td><a href="{% url 'app_doctor:route_detail' order.id %}">Посмотреть маршрут</a></td>
            {% else %}
            <td>добавте в маршрут</td>
            {% endif %}


            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}